[build]
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

# Facoltativo: forza regione EU (maggior vicinanza all'Italia)
[[functions.environment]]
  name = "AWS_LAMBDA_FUNCTION_MEMORY_SIZE"
  value = "1024"
