[build]
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

# se vuoi passare variabili d'ambiente, usa direttamente questa forma:
[functions.environment]
  STATION_ID = "2772110721"  # 👈 puoi anche lasciarlo vuoto e impostarlo dal pannello Netlify
